### ISSUE TITLE
this functionality is built into npm (npm version)

### ISSUE THREAD

**Issue by jasonkarns** [alexeyraspopov/node-bump#2]
Just wanted to note that this functionality is already built into npm by default.

`npm version <major | minor | patch | etc>`

https://docs.npmjs.com/cli/version

Granted, `npm version` only bumps `package.json` files. But it has version-level bumping by default. It does git-committing and git-tagging as well.

**Comment by alexeyraspopov** [comment]
Awesome, thanks for sharing. I'll update readme.
